image: node:20.9.0

stages:
  - test
  - deploy

cache:
  key:
    files:
      - yarn.lock
    prefix: yarn
  paths:
    - node_modules/

test:
  stage: test
  script:
    - yarn
    - yarn run lint
    - yarn run vitest run ./tests/unit
    - yarn playwright install --with-deps
    - yarn run playwright test
  artifacts:
    when: always
    paths:
      - test-results/
    reports:
      junit: test-results/*.xml
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
    - yarn
    - yarn build
    - cp -a dist/. public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
