services:
  web:
    container_name: 'hvv-tender-frontend'
    image: sampleproject
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./vite.config.ts:/app/vite.config.ts
      - ./public:/app/public
      - ./index.html:/app/index.html
      - ./tailwind.config.js:/app/tailwind.config.js
      - ./playwright.config.ts:/app/playwright.config.ts
