name: Build and Deploy Application

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  packages: write 
  pages: write
  id-token: write

concurrency:
  group: "deploy"
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Run ESLint
        run: yarn run lint

      - name: Run Unit Tests
        run: yarn run vitest run ./tests/unit

      - name: Install Playwright
        run: yarn playwright install --with-deps

      - name: Run Playwright tests
        run: yarn run playwright test

      - name: Build application
        run: yarn run build

      - name: Log in to GitHub Container Registry
        if: success()
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        if: success()
        run: |
          docker build -t ghcr.io/${{ github.repository }}/my-app:latest .

      - name: Push Docker image
        if: success()
        run: |
          docker push ghcr.io/${{ github.repository }}/my-app:latest

      - name: Setup Pages
        if: success()
        uses: actions/configure-pages@v4

      - name: Upload artifact
        if: success()
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"

      - name: Deploy to GitHub Pages
        if: success()
        id: deployment
        uses: actions/deploy-pages@v4
